@BASE_API=http://localhost:8081/api


### POST /api/evacuation-zones
POST {{BASE_API}}/evacuation-zones
Content-Type: application/json

{
    "ZoneID": "Z6",
    "LocationCoordinates": { "latitude": 16.436909150163707, "longitude": 102.83470331580656 },
    "NumberOfPeople": 5,
    "UrgencyLevel": 1
}


### POST /api/vehicles
POST {{BASE_API}}/vehicles
Content-Type: application/json

{
    "VehicleID": "V4",
    "Capacity": 70,
    "Type": "bus",  
    "LocationCoordinates": { "latitude": 16.451480804122994, "longitude": 102.85557431093233 },
    "Speed": 30
}

### POST /api/evacuations/plan
POST {{BASE_API}}/evacuations/plan
Content-Type: application/json

### POST /api/evacuations/status
GET {{BASE_API}}/evacuations/status
Content-Type: application/json
