@BASE_API=http://localhost:8081/api


### POST /api/evacuation-zones
POST {{BASE_API}}/evacuation-zones
Content-Type: application/json

{
    "ZoneID": "Z3",
    "LocationCoordinates": { "latitude": 13.7367, "longitude": 100.5231 },
    "NumberOfPeople": 100,
    "UrgencyLevel": 4
}


### POST /api/vehicles
POST {{BASE_API}}/vehicles
Content-Type: application/json

{
    "VehicleID": "V1",
    "Capacity": 70,
    "Type": "bus",  
    "LocationCoordinates": { "latitude": 16.451480804122994, "longitude": 102.85557431093233 },
    "Speed": 50
}

### POST /api/evacuations/plan -> Gen Plan
POST {{BASE_API}}/evacuations/plan
Content-Type: application/json

### GET /api/evacuations/status
GET {{BASE_API}}/evacuations/status
Content-Type: application/json

### PUT /api/evacuations/status
PUT {{BASE_API}}/evacuations/update
Content-Type: application/json

{
  "ZoneID": "Z3",
  "VehicleID": "V2",
  "PeopleMoved": 20
}