services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - postgres_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/redis.conf
    command: redis-server /redis.conf

volumes:
  postgres_db:
